name: Release Windows Installer

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          working-directory: backend

      - name: Build frontend
        shell: bash
        working-directory: frontend/looksyk
        run: |
          npm install
          npm run build --configuration=production

      - name: Build backend
        working-directory: backend
        run: cargo build --release

      - name: Package application wrapper
        shell: bash
        working-directory: application-wrapper/Looksyk
        run: |
          npm install
          npm run package

      - name: Create target directory and copy artifacts
        shell: bash
        run: |
          echo "delete old target"
          rm -rf target
          echo "old target deleted"
          echo "creating new target"
          mkdir -p target
          cp backend/target/release/looksyk.exe target/
          mkdir -p target/static
          cp -rf frontend/looksyk/dist/looksyk/browser/* target/static
          mkdir -p target/application-wrapper
          if [ -d "application-wrapper/Looksyk/out/looksyk-win32-x64" ]; then
            cp -r application-wrapper/Looksyk/out/looksyk-win32-x64/* target/application-wrapper
          else
            echo "Warning: could not find application-wrapper/Looksyk/out/looksyk-win32-x64"
            # for debugging, list the contents of the out directory
            ls -l application-wrapper/Looksyk/out
          fi
          echo "done"


      - name: Make Windows installer
        env:
          # This secret should be configured in your repository settings
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          cd application-wrapper/Looksyk
          npm install --save-dev @electron-forge/maker-squirrel
          npm run make -- --platform=win32 --arch=x64

      - name: Upload Windows Installer to Release
        run: |
          $release_tag = "${{ github.ref_name }}"
          $asset_path = "application-wrapper/Looksyk/out/make/squirrel.windows/x64/*"
          Get-ChildItem -Path $asset_path | ForEach-Object { gh release upload $release_tag $_.FullName --clobber }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}